Reduce Fio logs verbosity
EdgeApp/edge-currency-accountbased pull request #276
Opened 2021-04-17 12:03 UTC by thehobbit85

2021-04-17 15:20 UTC, paullinator requested changes

2021-04-17 15:20 UTC, paullinator commented on src/fio/fioEngine.js
> +        this.log(
This looks like an error in transaction creation which should not be silenced

2021-04-17 15:20 UTC, paullinator commented on src/fio/fioEngine.js
> +        this.log(
This looks like an error in transaction creation which should not be silenced

2021-04-17 15:28 UTC, thehobbit85 commented
I agree that it's an error in transaction and it should not be silenced, but, there are some inconsistencies between the result type we expect from the server to what we actually get, which cause this error to be triggered far more than it should. I do plan to talk to Andrew about a more permanent fix, but I thought that this is good enough until the next release.

2021-04-17 15:30 UTC, thehobbit85 commented
And the comment I wrote applies for both logs

2021-04-20 00:02 UTC, thehobbit85 commented
Got a verbal approval from Paul

2021-04-20 00:03 UTC, merged