Add Solana
EdgeApp/edge-currency-accountbased pull request #376
Opened 2022-02-04 10:24 UTC by peachbits

wip

Remaining unfinished/untested functions:
signTx
broadcastTx

2022-02-07 04:36 UTC, paullinator requested changes

2022-02-07 04:36 UTC, paullinator commented on src/solana/solanaEngine.js
> +    this.keypair = currencyPlugin.createKeyPair(
This should not happen on every engine creation. createKeyPair uses slow cryptography. This should only be done when needed to sign a transaction. The public key should be created at the time you import or create the private key and be returned in the keys object.

2022-02-07 04:36 UTC, paullinator commented on src/solana/solanaEngine.js
> +      this.error(`Error checking ${this.chainCode} address balance`, e)
This isn't really an error if the account is uninitiated. Can you differentiate a true error and only log that?

2022-02-07 04:36 UTC, paullinator commented on src/solana/solanaEngine.js
> +        txids = txids.concat(
Don't remove failed transactions if they incurred a fee to the user's wallet. Just like ETH, those are valid transactions, and the fee should still be shown. Set nativeamount to 0 and add it.

2022-02-07 04:36 UTC, paullinator commented on src/solana/solanaEngine.js
> +    let newestTxid = 0
Should be called `newestTxIndex`. It's not a txid

2022-02-07 04:36 UTC, paullinator commented on src/solana/solanaEngine.js
> +      this.otherData.newestTxid = txids[newestTxid + 1].signature
`newestTxid` has an inconsistent type. sometimes a number, sometimes a string. make it consistent.

2022-02-07 21:35 UTC, peachbits commented on src/solana/solanaPlugin.js
> +    const { parsedUri, edgeParsedUri } = this.parseUriCommon(
Yes it's standard bip21 https://github.com/solana-labs/solana-pay/blob/master/SPEC.md we'll need special handling for spl-token once we add token support

2022-02-08 16:42 UTC, paullinator approved these changes

2022-02-08 18:34 UTC, merged