Remove queries for internal transactions
EdgeApp/edge-currency-accountbased pull request #415
Opened 2022-06-05 23:33 UTC by paullinator

Internal transactions are by definition between contracts and don't affect the end balance of an EVM account. These queries were overwriting regular transactions with the same txid causing incorrect transaction amounts.

2022-06-08 17:58 UTC, peachbits requested changes

2022-06-08 17:58 UTC, peachbits commented on src/ethereum/ethNetwork.js
> +    if (
Remove this debugging log

2022-06-09 16:02 UTC, paullinator commented on src/ethereum/ethNetwork.js
> +    if (
good catch

2022-06-09 18:15 UTC, peachbits requested changes

2022-06-09 18:15 UTC, peachbits commented on src/ethereum/ethNetwork.js
> -  asAmberdataAccountsFuncs,
Duh I didn't catch these wouldn't be used anymore. Can you remove them the ethTypes too?

2022-06-10 19:36 UTC, peachbits commented
/rebase

2022-06-10 19:40 UTC, peachbits approved these changes

2022-06-10 19:40 UTC, merged