Engine cleanup
EdgeApp/edge-currency-accountbased pull request #469
Opened 2022-11-30 14:29 UTC by swansontec

This improves the relationship between the currency plugins, currency infos, and currency engines, so we can split the heavy crypto libraries out of the main bundle.

2022-11-30 21:31 UTC, peachbits requested changes
Really tiny comment to address otherwise approved

2022-11-30 21:31 UTC, peachbits commented on src/hedera/hederaTypes.ts
> +]
The otherMethodsNames value for Hedera, EOS, and FIO are all typed a little different. The one for EOS makes the most sense I think.

2022-12-01 21:16 UTC, swansontec commented on src/xrp/xrpEngine.ts
> +  otherData!: XrpWalletOtherData
Alternatively, you could make the engine responsible for defining an `XyzOtherData` type, and then typing `walletLocalData<XyzOtherData>`, so the type information flows cleanly into the helper class.

2022-12-01 22:07 UTC, peachbits approved these changes

2022-12-01 22:26 UTC, merged