Replace Shapeshift API with native RPC searchTx
EdgeApp/edge-currency-accountbased pull request #671
Opened 2023-11-17 07:28 UTC by peachbits

### CHANGELOG

Does this branch warrant an entry to the CHANGELOG?

- [ ] Yes
- [ ] No

### Dependencies

 none

### Description

 none

2023-11-18 02:08 UTC, paullinator requested changes

2023-11-18 02:08 UTC, paullinator commented on src/cosmos/CosmosEngine.ts
> +      this.currencyInfo.currencyCode !== coin.denom.toUpperCase()
if currencycode does match, but the address doesn't match as sender or recipient, why would we include this tx?

2023-11-18 02:08 UTC, paullinator commented on src/cosmos/CosmosEngine.ts
> +      } while (txCountTotal != null && txCountTotal > txCount && !earlyExit)
`txCountTotal` can never be null by this point.

2023-11-20 19:57 UTC, peachbits commented on src/cosmos/CosmosEngine.ts
> +    const tmClient = client['forceGetTmClient']()
It's protected so I need to suppress the error. I can use this or dot notation with ts-expect-error

2023-11-20 19:59 UTC, peachbits commented on src/cosmos/CosmosEngine.ts
> +              if (transferEvent == null) return []
remnant from using .map

2023-11-20 19:59 UTC, peachbits commented on src/cosmos/CosmosEngine.ts
> +              return coins.forEach(coin => {
remnant from using .map

2023-11-21 01:04 UTC, paullinator approved these changes

2023-11-21 01:04 UTC, paullinator commented
/rebase

2023-11-21 01:33 UTC, merged