Support signing non-hex messages
EdgeApp/edge-currency-accountbased pull request #804
Opened 2024-07-23 00:56 UTC by Jon-edge

Required for signing Bity orders

### CHANGELOG

Does this branch warrant an entry to the CHANGELOG?

- [x] Yes
- [ ] No

### Dependencies

 none

### Description

 none

2024-07-23 04:40 UTC, peachbits requested changes

2024-07-23 04:40 UTC, peachbits commented on src/ethereum/EthereumEngine.ts
> +          : Buffer.from(message)
I'm not sure it's a good idea to use Buffer.from without specifying the encoding. Instead maybe explicitly test for different types of strings and use base16 and base64 to create the uint8array and to support arbitrary text by using  Buffer.from(arg, 'ascii')

2024-07-29 17:47 UTC, Jon-edge reviewed
Dependencies updated. Now leaving signMessage unchanged, and implementing a generic signBytes()

2024-07-29 20:23 UTC, Jon-edge commented on src/ethereum/EthereumEngine.ts
> +      signBytes: (bytes: Uint8Array, privateKeys: EthereumPrivateKeys) => {
`EthereumUtils` requires signMessage... Is the ask to make the change across all plugins?

2024-07-29 22:56 UTC, peachbits approved these changes

2024-07-30 21:29 UTC, merged